# Generated by Django 5.1.3 on 2026-05-06 12:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('subtitle', models.TextField(verbose_name='Дэд тайлбар')),
                ('mission', models.TextField(verbose_name='Зорилго')),
                ('vision', models.TextField(verbose_name='Алсын хараа')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('icon', models.CharField(help_text='lucide icon name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Хуудасны нэр')),
                ('content_key', models.SlugField(unique=True, verbose_name='Түлхүүр үг (Slug)')),
                ('text_content', models.TextField(verbose_name='HTML Агуулга')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сайтын контент',
                'verbose_name_plural': 'Сайтын контентууд',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('startup', 'Startup Founder'), ('investor', 'Investor'), ('admin', 'Admin')], default='startup', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Байгууллагын нэр')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Регистрийн дугаар')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Вэбсайт')),
                ('representative_name', models.CharField(max_length=255, verbose_name='Төлөөлөх албан тушаалтан')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Холбоо барих мэйл')),
                ('investment_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хөрөнгө оруулалтын хэмжээ')),
                ('focus_industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сонирхдог салбар')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='investor_certificates/', verbose_name='Гэрчилгээний хуулбар')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Баталгаажсан эсэх')),
                ('address', models.CharField(default='Talbai', max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хөрөнгө оруулагч',
                'verbose_name_plural': 'Хөрөнгө оруулагчид',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='startupbackend.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='startupbackend.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Стартапын нэр')),
                ('industry', models.CharField(max_length=255, verbose_name='Салбар')),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Growth', 'Growth')], max_length=20, verbose_name='Хөгжүүлэлтийн шат')),
                ('pitch_deck_link', models.FileField(blank=True, max_length=500, null=True, upload_to='description/', verbose_name='Pitch Deck Link')),
                ('demo_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Demo / Website')),
                ('equity_offered', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Эзэмшил хувь (%)')),
                ('fund_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Татах дүн ($)')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цугласан хөрөнгө')),
                ('fund_purpose', models.TextField(verbose_name='Ашиглах зорилго')),
                ('description', models.TextField(verbose_name='Дэлгэрэнгүй тайлбар')),
                ('image_url', models.FileField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Images')),
                ('founder_name', models.CharField(max_length=255, verbose_name='Үүсгэн байгуулагчийн нэр')),
                ('email', models.EmailField(max_length=254, verbose_name='Email хаяг')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Profile')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стартап хүсэлт',
                'verbose_name_plural': 'Стартап хүсэлтүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='startupbackend.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='startupbackend.startup')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='startupbackend.startup'),
        ),
        migrations.CreateModel(
            name='StartupGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('percentage', models.IntegerField(help_text='График дээр харуулах өсөлтийн хувь', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='startupbackend.startup')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Стартап нэр')),
                ('description', models.TextField(verbose_name='Танилцуулга')),
                ('meeting_requested', models.BooleanField(default=False, verbose_name='Уулзалт хүссэн эсэх')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж байна'), ('approved', 'Зөвшөөрсөн'), ('rejected', 'Татгалзсан')], default='pending', max_length=20, verbose_name='Төлөв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='startupbackend.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='startupbackend.startup')),
            ],
            options={
                'verbose_name': 'Стартап хүсэлт',
                'verbose_name_plural': 'Стартап хүсэлтүүд',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('leader', 'Ахлагч'), ('member', 'Гишүүн')], default='member', max_length=20, verbose_name='Төрөл')),
                ('image', models.FileField(upload_to='team_members/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='startupbackend.startup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('startup', 'investor')},
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Хадгалсан огноо')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='startupbackend.startup', verbose_name='Стартап')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хадгалсан төсөл',
                'verbose_name_plural': 'Хадгалсан төслүүд',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'startup')},
            },
        ),
    ]
